### ISSUE TITLE
Apple Store Compliance

### ISSUE THREAD

**Issue by azazlhr** [leecrossley/cordova-plugin-background-task#2]
Hi,

I just want to clarify that, would the application which uses this plugin be in compliance with Apple Store rules? In other words, will Apple accept that app?

I'm asking this because there some similar plugins on github and they are not in compliance with Apple Store rules e.g. [cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode) . Did anyone use this plugin in their app and published it on Apple Store without any issue?

Any answer or support will be much appreciated. Thanks.

**Comment by leecrossley** [comment]
https://itunes.apple.com/gb/app/sprint-social/id975135816 uses this plugin and was approved. It allows you to run JavaScript when the app is active and for 3 minutes after the app is suspended, which is compliant.

**Comment by azazlhr** [comment]
Thanks Lee for your quick response.
It's good to know that apps are using this plugin without any constraint.
