### ISSUE TITLE
Determine Is in Suspended Mode

### ISSUE THREAD

**Issue by azazlhr** [leecrossley/cordova-plugin-background-task#3]
Hi,

I know currently using this plugin, it's not possible to determine if App is running in suspended mode(for last 3 minutes). Can you please inform me if it would be possible in future updates of this plugin, or you know/have any other plugin developed which serves the requirements/purpose. Thanks.

**Comment by leecrossley** [comment]
You should use the Cordova [pause](https://cordova.apache.org/docs/en/5.0.0/cordova_events_events.md.html#pause) event to detect when an application was sent to the background

`document.addEventListener("pause", yourCallbackFunction, false);`
