### ISSUE TITLE
Background stops after a while

### ISSUE THREAD

**Issue by scrawner** [leecrossley/cordova-plugin-background-task#4]
I think that apple is finishing background task after a while.
Im running a code that uses setInterval. Which means that while in background the app keeps sending information to the server (tracking location). I suppose iOS is stoping that for spending a long time in background.
Any suggestion?

**Comment by leecrossley** [comment]
> Allows you to run JavaScript when the app is active and for 3 minutes after the app is suspended

This is an Apple limitation, as this mechanism is really designed for cleaning up. There are other ways to specifically track location in the background, see [here](http://plugreg.com/plugin/christocracy/cordova-plugin-background-geolocation) or there are other plugins.
